language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm who
install:
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "e/LrTOmOzGZ8jpr7Wbh5mLTdiFla5SyPOxM8dl6Rt0ZjFirvDwCfh7W/DMvQ5y70u+FDdukQrFbFWTJXiRNpOGENlTR7L35jZeKt5tu2pzfiVTn9Lo1hraj73Jp7j/lZ09/zVu9jX+kfadVj6OMV4bazn8d8T3l9+wb2Bb0OnT7fXSe7Zw8LKbwHoCtJJeYuYY3QYQKsEW5Mi8h9eW3UrmzWW8EemvzMhYpUZNpwu4/Ynr24EU1C1cy591px3LpcTR+zBqOArsuidjc33gWor7cZkkGhDdgU+35y5PfvDKnjgis6J/d+qM+7pUEIHEOtPuHVqwvTXGJ1wZRJJF491Z5M46CRaIVys4NEl4C0QfA8Zwb3A3kOQoISsw5IBkTBi7zDD4sybo8crCQR/W9q9PaiZM5iSY+sJU2hn/OAExng+PxQ4RH6sa1SjlH+TQLJ4HrnWDSJPHKYbFDcMK6tgbEzUT6QrcUS3hWqIfAIlEELLEBHGQzslophEO9tf71uajTQQ5t9FA2xjQrkrg+wT5LUwoVLXX2ZCytQ8OAq/A+CvtGlUgvEetpE5rerYWEiy5ohpqHvliO4Ewd0mItg6UKNgORBFtLb5lcv0d4s2Ke0LCGeXJh1ATMzCF8FRm/9YDzJC5lEzzGmfRTg+ZopmACcoMh7OjPaZ1jxAkWsQqg="
